NTierProject.WebUI/Areas/Admin/Controllers/AppUserController.cs
using NtierProject.SERVICE.Option;
using NTierProject.COMMON.MyTools;
using NTierProject.MODEL.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NTierProject.WebUI.Areas.Admin.Controllers
{
    public class AppUserController : Controller
    {
        AppUserService appUser = new AppUserService();
        public ActionResult Index()
        {
            return View(appUser.GetActive().OrderByDescending(x => x.CreatedDate).ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(AppUser model, HttpPostedFileBase ImagePath)
        {
            model.ID = Guid.NewGuid();
            model.ImagePath = ImageUploader.UploadSingleImage("~/Uploads/Users/", ImagePath);
            appUser.Add(model);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(Guid Id)
        {
            return View(appUser.GetById(Id));
        }

        [HttpPost]
        public ActionResult Edit(AppUser model, HttpPostedFileBase ImagePath)
        {
            if (ImagePath != null)
            {
                model.ImagePath = ImageUploader.UploadSingleImage("~/Uploads/Users/", ImagePath);
                appUser.Update(model);
            }
            else
            {
                model.ImagePath = appUser.GetById(model.ID).ImagePath;
                appUser.Update(model);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid Id)
        {
            return View(appUser.GetById(Id));
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(Guid Id)
        {
            appUser.Remove(appUser.GetById(Id));
            appUser.Save();
            return RedirectToAction("Index");
        }
    }
}

NTierProject.WebUI/Areas/Admin/Views/AppUser/Create.cshtml
@using NTierProject.CORE.Enums
@{
    ViewBag.Title = "Kullanıcı Ekle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                @ViewBag.Title
            </header>
            <div class="panel-body">
                @using (Html.BeginForm("Create", "AppUser", FormMethod.Post, new { enctype = "multipart/form-data", role = "form" }))
                {
                    <div class="form-group">
                        <label for="Name">Adı</label>
                        <input type="text" class="form-control" id="Name" name="Name" placeholder="İsim giriniz..">
                    </div>
                    <div class="form-group">
                        <label for="SurName">Soyadı</label>
                        <input type="text" class="form-control" id="SurName" name="SurName" placeholder="Soyisim giriniz..">
                    </div>
                    <div class="form-group">
                        <label for="UserName">Kullanıcı Adı</label>
                        <input type="text" class="form-control" id="UserName" name="UserName" placeholder="Kullanıcı adı giriniz..">
                    </div>
                    <div class="form-group">
                        <label for="Password">Şifre</label>
                        <input type="password" class="form-control" id="Password" name="Password" placeholder="Şifre giriniz..">
                    </div>
                    <div class="form-group">
                        <label for="ConfirmPassword">Şifre Tekrar</label>
                        <input type="password" class="form-control" id="ConfirmPassword" name="ConfirmPassword" placeholder="Şifreyi tekrar giriniz..">
                    </div>
                    <div class="form-group">
                        <label for="Email">Email</label>
                        <input type="email" class="form-control" id="Email" name="Email" placeholder="Email adresi giriniz..">
                    </div>
                    <div class="form-group">
                        <label for="Address">Adres</label>
                        <textarea class="form-control" id="Address" name="Address" placeholder="Adres giriniz.."></textarea>
                    </div>
                    <div class="form-group">
                        <label for="PhoneNumber">Telefon</label>
                        <input type="tel" class="form-control" id="PhoneNumber" name="PhoneNumber" placeholder="Telefon giriniz..">
                    </div>
                    <div class="form-group">
                        <label for="BirthDate">Doğum Tarihi</label>
                        <input type="date" class="form-control" id="BirthDate" name="BirthDate">
                    </div>
                    <div class="form-group">
                        <label for="Role">Yetki</label>
                        <select class="form-control" id="Role" name="Role">
                            @foreach (var item in Enum.GetValues(typeof(Role)))
                            {
                                if ((Role)item == Role.Member)
                                {
                                    <option selected>@item</option>
                                }
                                else
                                {
                                    <option>@item</option>
                                }
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="isActive">Aktif/Pasif</label>
                        <select class="form-control" id="isActive" name="isActive">
                            <option value="true">Aktif</option>
                            <option value="false">Pasif</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="ImagePath">Görsel Seç</label>
                        <input type="file" class="form-control" id="ImagePath" name="ImagePath" />
                    </div>
                    <button type="submit" class="btn btn-info">Kaydet</button>
                    <a href="@Url.Action("Index", "AppUser")" class="btn btn-default">Kullanıcılara geri dön</a>
                }
            </div>
        </section>
    </div>
</div>

NTierProject.WebUI/Areas/Admin/Views/AppUser/Delete.cshtml
@model NTierProject.MODEL.Entities.AppUser

@{
    ViewBag.Title = "Kullanıcı Sil";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    @ViewBag.Title
                </header>
                <div class="panel-body">
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Ad, Soyad : </strong>@Model.Name @Model.SurName</li>
                        <li class="list-group-item"><strong>Kullanıcı Adı : </strong>@Model.UserName</li>
                        <li class="list-group-item"><strong>Email : </strong>@Model.Email</li>
                        <li class="list-group-item">
                            <img src="@Model.ImagePath" style="width:64px; height:64px" />
                        </li>
                    </ul>
                    @using (Html.BeginForm())
                    {
                        <button type="submit" class="btn btn-info">Sil</button>
                        <a href="@Url.Action("Index", "AppUser")" class="btn btn-default">Kullanıcılara geri dön</a>
                    }
                </div>
            </section>
        </div>
    </div>

NTierProject.WebUI/Areas/Admin/Views/AppUser/Edit.cshtml
@using NTierProject.CORE.Enums
@model AppUser
@{
    ViewBag.Title = "Kullanıcı Düzenle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                @ViewBag.Title
            </header>
            <div class="panel-body">
                @using (Html.BeginForm("Edit", "AppUser", FormMethod.Post, new { enctype = "multipart/form-data", role = "form" }))
                {
                    <div class="form-group">
                        <label for="Name">Adı</label>
                        <input type="text" class="form-control" id="Name" name="Name" placeholder="İsim giriniz.." value="@Model.Name">
                    </div>
                    <div class="form-group">
                        <label for="SurName">Soyadı</label>
                        <input type="text" class="form-control" id="SurName" name="SurName" placeholder="Soyisim giriniz.." value="@Model.SurName">
                    </div>
                    <div class="form-group">
                        <label for="UserName">Kullanıcı Adı</label>
                        <input type="text" class="form-control" id="UserName" name="UserName" placeholder="Kullanıcı adı giriniz.." value="@Model.UserName">
                    </div>
                    <div class="form-group">
                        <label for="Password">Şifre</label>
                        <input type="password" class="form-control" id="Password" name="Password" placeholder="Şifre giriniz.." value="@Model.Password">
                    </div>
                    <div class="form-group">
                        <label for="Email">Email</label>
                        <input type="email" class="form-control" id="Email" name="Email" placeholder="Email adresi giriniz.." value="@Model.Email">
                    </div>
                    <div class="form-group">
                        <label for="Address">Adres</label>
                        <textarea class="form-control" id="Address" name="Address" placeholder="Adres giriniz..">@Model.Address</textarea>
                    </div>
                    <div class="form-group">
                        <label for="PhoneNumber">Telefon</label>
                        <input type="tel" class="form-control" id="PhoneNumber" name="PhoneNumber" placeholder="Telefon giriniz.." value="@Model.PhoneNumber">
                    </div>
                    <div class="form-group">
                        <label for="BirthDate">Doğum Tarihi</label>
                        <input type="text" class="form-control" id="BirthDate" name="BirthDate" value="@(((DateTime)(Model.BirthDate)).ToShortDateString())">
                    </div>
                    <div class="form-group">
                        <label for="Role">Yetki</label>
                        <select class="form-control" id="Role" name="Role">
                            @foreach (var item in Enum.GetValues(typeof(Role)))
                            {
                                if ((Role)item == Model.Role)
                                {
                                    <option selected>@item</option>
                                }
                                else
                                {
                                    <option>@item</option>
                                }
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="isActive">Aktif/Pasif</label>
                        <select class="form-control" id="isActive" name="isActive">
                            <option @(Model.isActive == true ? "selected" : "") value="true">Aktif</option>
                            <option @(Model.isActive == false ? "selected" : "") value="false">Pasif</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <img src="@Model.ImagePath" style="width:64px; height:64px" />
                    </div>
                    <div class="form-group">
                        <label for="ImagePath">Görsel Seç</label>
                        <input type="file" class="form-control" id="ImagePath" name="ImagePath" />
                    </div>
                    <input type="hidden" name="ID" value="@Model.ID" />
                    <button type="submit" class="btn btn-info">Kaydet</button>
                    <a href="@Url.Action("Index", "AppUser")" class="btn btn-default">Kullanıcılara geri dön</a>
                }
            </div>
        </section>
    </div>
</div>

NTierProject.WebUI/Areas/Admin/Views/AppUser/Index.cshtml
@using NTierProject.CORE.Enums
@model List<AppUser>
@{
    ViewBag.Title = "Kullanıcılar";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                @ViewBag.Title
            </header>
            <div class="panel-body">
                <div class="clearfix">
                    <div class="btn-group">
                        <a href="@Url.Action("Create", "AppUser")" class="btn btn-success">
                            Yeni Ekle
                            <i class="icon-plus"></i>
                        </a>
                    </div>
                </div>
                <table class="table table-striped table-advance table-hover">
                    <thead>
                        <tr>
                            <th><i class="icon-picture"></i> Görsel</th>
                            <th><i class="icon-user"></i> Adı</th>
                            <th><i class="icon-user"></i> Soyadı</th>
                            <th><i class="icon-user"></i> Kullanıcı Adı</th>
                            <th><i class="icon-lock"></i> Şifre</th>
                            <th><i class="icon-envelope"></i> Email</th>
                            <th><i class="icon-map-marker"></i> Adres</th>
                            <th><i class="icon-phone"></i> Telefon</th>
                            <th><i class="icon-calendar"></i> Doğum Tarihi</th>
                            <th><i class="icon-level-down"></i> Seviye</th>
                            <th><i class="icon-ok"></i> Aktif/Pasif</th>
                            <th><i class="icon-calendar"></i> Oluşturma Tarihi</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <img src="@item.ImagePath" style="width:32px; height:32px" />
                                </td>
                                <td>@item.Name</td>
                                <td>@item.SurName</td>
                                <td>@item.UserName</td>
                                <td>@item.Password</td>
                                <td>@item.Email</td>
                                <td>@item.Address</td>
                                <td>@item.PhoneNumber</td>
                                <td>@(((DateTime)item.BirthDate).ToShortDateString())</td>
                                @if (item.Role == Role.Banned)
                                {
                                    <td><span class="label label-danger label-mini">Yasaklı</span></td>
                                }
                                else if (item.Role == Role.Member)
                                {
                                    <td><span class="label label-primary label-mini">Üye</span></td>
                                }
                                else
                                {
                                    <td><span class="label label-success label-mini">Yönetici</span></td>
                                }

                                @if (item.isActive)
                                {
                                    <td><span class="label label-success label-mini">Aktif</span></td>
                                }
                                else
                                {
                                    <td><span class="label label-danger label-mini">Pasif</span></td>
                                }
                                <td>@item.CreatedDate</td>
                                <td>
                                    <a href="@Url.Action("Edit", "AppUser", new { id=item.ID })" class="btn btn-primary btn-xs"><i class="icon-pencil"></i></a>
                                    <a href="@Url.Action("Delete", "AppUser", new { id=item.ID })" class="btn btn-danger btn-xs"><i class="icon-trash "></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</div>