NTierProject.WebUI/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NtierProject.SERVICE.Option;
using NTierProject.MODEL.Context;
using NTierProject.MODEL.Entities;

namespace NTierProject.WebUI.Areas.Admin.Controllers
{
    public class CategoryController : Controller
    {
        CategoryService db = new CategoryService();

        // GET: Admin/Category
        public ActionResult Index()
        {
            return View(db.GetAll());
        }

        // GET: Admin/Category/Details/5
        public ActionResult Details(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.GetById(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Admin/Category/Create
        public ActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                category.ID = Guid.NewGuid();
                db.Add(category);
                db.Save();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Admin/Category/Edit/5
        public ActionResult Edit(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.GetById(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Category category)
        {
            if (ModelState.IsValid)
            {
                db.Update(category);
                db.Save();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Admin/Category/Delete/5
        public ActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.GetById(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Admin/Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Category category = db.GetById(id);
            db.Remove(category);
            db.Save();
            return RedirectToAction("Index");
        }

     
    }
}

NTierProject.WebUI/Areas/Admin/Controllers/SubCategoryController.cs
using NtierProject.SERVICE.Option;
using NTierProject.MODEL.Entities;
using NTierProject.WebUI.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NTierProject.WebUI.Areas.Admin.Controllers
{
    public class SubCategoryController : Controller
    {
        SubCategoryService sub = new SubCategoryService();
        CategoryService category = new CategoryService();
        public ActionResult Index()
        {
            return View(sub.GetActive());
        }

        public ActionResult Add()
        {
            return View(category.GetActive());
        }

        [HttpPost]
        public ActionResult Add(SubCategory data)
        {
            data.ID = Guid.NewGuid();
            sub.Add(data);

            return RedirectToAction("Index");
        }
        public ActionResult Update(Guid id)//Bilgisayar
        {
            SubCategoryVM model = new SubCategoryVM();
            model.SubCategory = sub.GetById(id);
            model.Categories = category.GetActive();
            return View(model);
        }

        [HttpPost]
        public ActionResult Update(SubCategory model)
        {
            sub.Update(model);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid id)
        {
            var deleted = sub.GetById(id);
            sub.Remove(deleted);
            return RedirectToAction("Index");
        }
    }
}

NTierProject.WebUI/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="~/Content/adminTheme/img/favicon.png">

    <title>NTierProject</title>

    <!-- Bootstrap core CSS -->
    <link href="~/Content/adminTheme/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/adminTheme/css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="~/Content/adminTheme/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/adminTheme/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen" />
    <link rel="stylesheet" href="~/Content/adminTheme/css/owl.carousel.css" type="text/css">
    <!-- Custom styles for this template -->
    <link href="~/Content/adminTheme/css/style.css" rel="stylesheet">
    <link href="~/Content/adminTheme/css/style-responsive.css" rel="stylesheet" />

</head>

<body>

    <section id="container">
        <!--header start-->
        <header class="header white-bg">
            <div class="sidebar-toggle-box">
                <div data-original-title="Toggle Navigation" data-placement="right" class="icon-reorder tooltips"></div>
            </div>
            <!--logo start-->
            <a href="~/Content/adminTheme/index.html" class="logo">Flat<span>lab</span></a>
            <!--logo end-->
            <div class="nav notify-row" id="top_menu">
                <!--  notification start -->
                <ul class="nav top-menu">
                </ul>
                <!--  notification end -->
            </div>
            <div class="top-nav ">
                <!--search & user info start-->
                <ul class="nav pull-right top-menu">
                    <li>
                        <input type="text" class="form-control search" placeholder="Search">
                    </li>
                    <!-- user login dropdown start-->
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="~/Content/adminTheme/#">
                            <img alt="" src="~/Content/adminTheme/img/avatar1_small.jpg">
                            <span class="username">Jhon Doue</span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu extended logout">
                            <div class="log-arrow-up"></div>
                            <li><a href="~/Content/adminTheme/#"><i class=" icon-suitcase"></i>Profile</a></li>
                            <li><a href="~/Content/adminTheme/#"><i class="icon-cog"></i> Settings</a></li>
                            <li><a href="~/Content/adminTheme/#"><i class="icon-bell-alt"></i> Notification</a></li>
                            <li><a href="~/Content/adminTheme/login.html"><i class="icon-key"></i> Log Out</a></li>
                        </ul>
                    </li>
                    <!-- user login dropdown end -->
                </ul>
                <!--search & user info end-->
            </div>
        </header>
        <!--header end-->
        <!--sidebar start-->
        @Html.Partial("_SidebarPartial")
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">

                <!--Start Content-->
                
              @RenderBody()

                <!--End Content-->
            </section>
        </section>
        <!--main content end-->
        <!--footer start-->
        <footer class="site-footer">
            <div class="text-center">
                2013 &copy; FlatLab by VectorLab.
                <a href="~/Content/adminTheme/#" class="go-top">
                    <i class="icon-angle-up"></i>
                </a>
            </div>
        </footer>
        <!--footer end-->
    </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="~/Content/adminTheme/js/jquery.js"></script>
    <script src="~/Content/adminTheme/js/jquery-1.8.3.min.js"></script>
    <script src="~/Content/adminTheme/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="~/Content/adminTheme/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="~/Content/adminTheme/js/jquery.scrollTo.min.js"></script>
    <script src="~/Content/adminTheme/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="~/Content/adminTheme/js/jquery.sparkline.js" type="text/javascript"></script>
    <script src="~/Content/adminTheme/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script>
    <script src="~/Content/adminTheme/js/owl.carousel.js"></script>
    <script src="~/Content/adminTheme/js/jquery.customSelect.min.js"></script>
    <script src="~/Content/adminTheme/js/respond.min.js"></script>

    <script class="include" type="text/javascript" src="~/Content/adminTheme/js/jquery.dcjqaccordion.2.7.js"></script>

    <!--common script for all pages-->
    <script src="~/Content/adminTheme/js/common-scripts.js"></script>

    <!--script for this page-->
    <script src="~/Content/adminTheme/js/sparkline-chart.js"></script>
    <script src="~/Content/adminTheme/js/easy-pie-chart.js"></script>
    <script src="~/Content/adminTheme/js/count.js"></script>

    <script>

      //owl carousel

      $(document).ready(function() {
          $("#owl-demo").owlCarousel({
              navigation : true,
              slideSpeed : 300,
              paginationSpeed : 400,
              singleItem : true,
			  autoPlay:true

          });
      });

      //custom select box

      $(function(){
          $('select.styled').customSelect();
      });

    </script>

</body>
</html>

NTierProject.WebUI/Areas/Admin/Views/Shared/_SidebarPartial.cshtml
<aside>
    <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu" id="nav-accordion">
            <li>
                <a class="active" href="@Url.Action("Index","Home")">
                    <i class="icon-dashboard"></i>
                    <span>Panel</span>
                </a>
            </li>

            <li class="sub-menu">
                <a href="~/Content/adminTheme/javascript:;">
                    <i class="icon-folder-close"></i>
                    <span>Kategori</span>
                </a>
                <ul class="sub">
                    <li><a href="@Url.Action("Index","Category")">Kategoriler</a></li>
                    <li><a href="@Url.Action("Index","SubCategory")">Alt Kategoriler</a></li>
                    <li><a href="@Url.Action("Create","Category")">Kategori Ekle</a></li>
                </ul>
            </li>

            <li class="sub-menu">
                <a href="~/Content/adminTheme/javascript:;">
                    <i class="icon-shopping-cart"></i>
                    <span>Ürünler</span>
                </a>
                <ul class="sub">
                    <li><a href="~/Content/adminTheme/general.html">Hepsi</a></li>
                    <li><a href="~/Content/adminTheme/buttons.html">Ürün Ekle</a></li>
                </ul>
            </li>

            <li class="sub-menu">
                <a href="~/Content/adminTheme/javascript:;">
                    <i class="icon-tag"></i>
                    <span>Siparişler</span>
                </a>
                <ul class="sub">
                    <li><a href="~/Content/adminTheme/grids.html">Sipariş Listesi</a></li>
                </ul>
            </li>
            <li class="sub-menu">
                <a href="~/Content/adminTheme/javascript:;">
                    <i class="icon-tasks"></i>
                    <span>Sipariş Detay</span>
                </a>
                <ul class="sub">
                    <li><a href="~/Content/adminTheme/form_component.html">Sipariş Detayları</a></li>
                </ul>
            </li>
            <li class="sub-menu">
                <a href="~/Content/adminTheme/javascript:;">
                    <i class="icon-user-md"></i>
                    <span>Kullanıcılar</span>
                </a>
                <ul class="sub">
                    <li><a href="~/Content/adminTheme/basic_table.html">Tüm Kullanıcılar</a></li>
                    <li><a href="~/Content/adminTheme/responsive_table.html">Kullanıcı Ekle</a></li>
                </ul>
            </li>
        </ul>
        <!-- sidebar menu end-->
    </div>
</aside>